name: Weekly

on:
  schedule:
    - cron: '48 0 * * 0'

jobs:
  weekly:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: ["1.65", stable]
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.rust}}
    - run: cargo build --workspace
